Repository Marco-Christiani/zigrad, pull requests merged in 2025-06, with the labels that each got.

#65 Add Earthly system test workflow
  .github/workflows/system-tests.yml
Labels: codex

#75 74 cicd concurrency triggers verification tests cache
  .github/workflows/format-check.yml
  .github/workflows/prune-cache.yml
  .github/workflows/update-docs.yml
  src/cuda/root.zig
Labels: CI/CD

#73 Caching Allocator and Refactoring
  build.zig
  examples/mnist/src/dataset.zig
  examples/mnist/src/main-simple.zig
  examples/mnist/src/model.zig
  src/allocators.zig
  src/allocators/arena_unmanaged.zig
  src/allocators/block_pool.zig
  src/allocators/caching_allocator.zig
  src/allocators/constants.zig
  src/allocators/device_data.zig
  src/allocators/order_list.zig
  src/cuda/CMakeLists.txt
  src/cuda/blas/contraction.cu
  src/cuda/blas/permutate.cu
  src/cuda/blas/reduce.cu
  src/cuda/blas_conflux.h
  src/cuda/cuda_utils.cu
  src/cuda/cuda_utils.h
  src/cuda/cutensor_utils.cu
  src/cuda/decls.h
  src/device.zig
  src/device/caching_allocator.zig
  src/device/cuda_device.zig
  src/device/device_reference.zig
  src/device/host_device.zig
  src/device/opspec.zig
  src/device/root.zig
  src/graph.zig
  src/graph/backward_context.zig
  src/graph/builder.zig
  src/graph/node.zig
  src/main.zig
  src/ndarray.zig
  src/ndtensor.zig
  src/nn/conv_utils.zig
  src/nn/loss.zig
  src/nn/tests/test_loss.zig
  src/zigrad.zig
Labels: enhancement
